'''
all the unit index pages
'''

unitIdx = list()
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_3.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_A.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_B.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_C.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_D.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_E.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_F.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_G.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_H.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_I.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_J.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_K.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_L.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_M.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_N.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_O.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_P.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_Q.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_R.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_S.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_T.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_U.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_V.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_W.html")
unitIdx.append("http://handbook.curtin.edu.au/units/indexes/units_X.html")